name: code-climate
on:
  push:
    branches:
      - master
      - 'pr/*'
  pull_request:
jobs:
  code-climate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version-file: go.mod
      - uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER_ID }}
        with:
          coverageCommand: make test
          coverageLocations: "coverage.out:gocov"
          prefix: github.com/screwyprof/cqrs
